module.exports = {
  sidebar: {
    'Material Table': [
      'getting-started/about',
      'getting-started/install',
      'getting-started/instance',
    ],
    Features: [
      "features/feature_actions",
      "features/feature_component_overriding",
      "features/feature_custom_column_rendering",
      "features/feature_detail_panel",
      "features/feature_editable",
      "features/feature_export",
      "features/feature_filtering",
      "features/feature_grouping",
      "features/feature_localization",
      "features/feature_remote_data",
      "features/feature_search",
      "features/feature_selection",
      "features/feature_sorting",
      "features/feature_styling",
      "features/feature_tree_data",
    ],
    API: [
      {
        "Props": [
          'api/props/mt_prop_actions',
          'api/props/mt_prop_columns',
          'api/props/mt_prop_components',
          'api/props/mt_prop_data',
          'api/props/mt_prop_detailPanel',
          'api/props/mt_prop_editable',
          'api/props/mt_prop_icons',
          'api/props/mt_prop_isLoading',
          'api/props/mt_prop_localization',
          'api/props/mt_prop_onChangePage',
          'api/props/mt_prop_onChangeRowsPerPage',
          'api/props/mt_prop_onChangeColumnHidden',
          'api/props/mt_prop_onColumnDragged',
          'api/props/mt_prop_onGroupRemoved',
          'api/props/mt_prop_onOrderChange',
          'api/props/mt_prop_onRowClick',
          'api/props/mt_prop_onSelectionChange',
          'api/props/mt_prop_onTreeExpandChange',
          'api/props/mt_prop_onSearchChange',
          'api/props/mt_prop_options',
          'api/props/mt_prop_parentChildData',
          'api/props/mt_prop_style',
          'api/props/mt_prop_tableRef',
          'api/props/mt_prop_title',
        ],
        Components: [
          'api/components/component_m_table_action',
          'api/components/component_m_table_actions',
          'api/components/component_m_table_body-row',
          'api/components/component_m_table_body',
          'api/components/component_m_table_cell',
          'api/components/component_m_table_edit-field',
          'api/components/component_m_table_edit-row',
          'api/components/component_m_table_filter-row',
          'api/components/component_m_table_group-row',
          'api/components/component_m_table_groupbar',
          'api/components/component_m_table_header',
          'api/components/component_m_table_pagination',
          'api/components/component_m_table_stepped-pagination',
          'api/components/component_m_table_toolbar',
        ],
        // "In Depth": [
        //   "api/in-depth/details_component_overriding"
        // ],
      },
    ],

  },
};